/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_bienvenuez (void);
GtkWidget* create_ajouterz2 (void);
GtkWidget* create_modifierz3 (void);
GtkWidget* create_supprimerz4 (void);
GtkWidget* create_chercherz6 (void);
GtkWidget* create_listedesetudiants (void);
GtkWidget* create_gestionetudiant (void);
GtkWidget* create_modifieretudiant (void);
GtkWidget* create_chercheretudiant (void);
GtkWidget* create_reclamation (void);
GtkWidget* create_ajouterreclamation (void);
GtkWidget* create_modifierreclamation (void);
GtkWidget* create_chercherreclamation (void);
GtkWidget* create_inscription (void);
GtkWidget* create_authen (void);
GtkWidget* create_Admin (void);
GtkWidget* create_dashboard_utilisateur (void);
GtkWidget* create_mod_utilisateur (void);
GtkWidget* create_af_utilisateur (void);
GtkWidget* create_aj_utilisateur (void);
GtkWidget* create_recherche (void);
GtkWidget* create_dashboard (void);
GtkWidget* create_mod (void);
GtkWidget* create_af (void);
GtkWidget* create_aj (void);
GtkWidget* create_dashboard6 (void);
GtkWidget* create_window1ac (void);
GtkWidget* create_window2ac (void);
GtkWidget* create_window3ac (void);
GtkWidget* create_window4ac (void);
GtkWidget* create_window5ac (void);
GtkWidget* create_start (void);
