/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *bienvenuez;
  GtkWidget *ajouterz2;
  GtkWidget *modifierz3;
  GtkWidget *supprimerz4;
  GtkWidget *chercherz6;
  GtkWidget *meilleurm;

GtkWidget *listedesetudiants;
GtkWidget *gestionetudiant;
GtkWidget *modifieretudiant;
GtkWidget *chercheretudiant;

GtkWidget *reclamation, *treeview1az;
GtkWidget *ajouterreclamation;
GtkWidget *supp_tr;
GtkWidget *modifierreclamation;

 GtkWidget *inscription;
  GtkWidget *authen;
  GtkWidget *Admin;

 GtkWidget *dashboard_utilisateur;
  GtkWidget *mod_utilisateur;
  GtkWidget *af_utilisateur;
  GtkWidget *aj_utilisateur;

GtkWidget *dashboard;
  GtkWidget *mod;
  GtkWidget *af;
  GtkWidget *aj;
GtkWidget *dashboard6;

GtkWidget *window1ac;
  GtkWidget *window2ac;
  GtkWidget *window3ac;
  GtkWidget *window4ac;
  GtkWidget *window5ac;
GtkWidget *start;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  

 


start = create_start ();
  gtk_widget_show (start);
  
  gtk_main ();


  return 0;
}

